"""empty message

Revision ID: f374aba29519
Revises: ffa3f0d49996
Create Date: 2023-10-04 12:17:05.238132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f374aba29519'
down_revision = 'ffa3f0d49996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_lastname_key', type_='unique')
        batch_op.drop_constraint('user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.create_unique_constraint('user_lastname_key', ['lastname'])

    # ### end Alembic commands ###
